### ISSUE TITLE
Duplicate Tock Report Populated

### ISSUE THREAD

**Issue by d-kenny** [18F/tock#626] opened 2017-04-07 17:24 UTC
Upon clicking save, my screen refreshed and all of the respective tock lines appeared again so I now had two of each (my apologies, forgot to take a screenshot).

**Comment by ccostino** [comment] 2017-08-18 20:26
Hey @d-kenny!  I'm closing as a duplicate of #642; the likely culprit is because of Tock being open in multiple tabs.  We'll work on a solution in the future to prevent this, but for now the work-around is as follows:

1. Close all tabs with Tock
2. Reopen Tock
3. Delete any duplicate entries
4. Submit again

if this doesn't help still or you noticed the behavior happen because of a different reason(s), then please re-open and let us know what happened!

**Closed** 2017-08-18 20:27 UTC
