### ISSUE TITLE
Remediate and assess CircleCI config

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#943] opened 2019-12-23 15:37 UTC
It's been awhile since we've revisited our circleCI setup for releases, testing, and recycling of the production instance.

Let's take a look  at `config.yml` to address two known issue and see if there are opportunities to simplify, modernize, or otherwise improve our usage of circleCI. 

### Known issues
- The `recycle_production` job is executing on branches other than `master`
- The `recycle_production` job intermittently fails

### We'll know we're done when

- [ ] The above issues have been resolved
- [x] `config.yml` has been reviewed and updated if necessary

**Comment by adunkman** [comment] 2019-12-27 18:04
I can take a look here — it looks like the deployment docker image [18fgsa/cloud-foundry-cli](https://hub.docker.com/r/18fgsa/cloud-foundry-cli) hasn’t been published for 2 years, which might be leading to our intermittent failures.

**Comment by Jkrzy** [comment] 2019-12-30 13:43
This is the cloudfoundry plugin being used for the instance recycling: https://github.com/rogeruiz/cf-recycle-plugin

And here's what a failure, time-out after ~5 hours, looks like in CircleCI: https://circleci.com/gh/18F/tock/5391

**Comment by adunkman** [comment] 2020-01-03 21:02
> The `recycle_production` job is executing on branches other than `master`

I can’t seem to find evidence of this in recent builds, and appears to have been fixed in #897 (f27fe7689975d1bc7457e066e3c8f04fb3e04c80).

**Comment by adunkman** [comment] 2020-01-03 21:57
Confirmed the hunch — intermittent failures are due to conflicting `recycle_production` jobs. 

Conflicting jobs happen often because the `hjb/try-uswds` branch (missing the commit from #897 above) and `master` both get triggered for scheduled runs at the same time. 

Short-term fix: merge master into `hjb/try-uswds` or delete it? @hbillings, is this branch still useful?

Long-term fix: prevent concurrent running jobs from conflicting with each other. I’ll do a bit of poking about here, but will time box it.

**Comment by adunkman** [comment] 2020-01-06 16:30
I’ve merged master to `hjb/try-uswds` to address the immediate issue, and my 2 hour timebox has expired — the best possible way to prevent concurrent restarts from conflicting with each other is currently switching from a restart job to a deployment job, and performing a [rolling app deployment](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html), which would cause the latest re-deploy to win, which is acceptable: 

> If you push app before your previous push command for the same app has completed, your first push gets interrupted. Until the last deployment completes, there may be many versions of the app running at once. Eventually, the app runs the code from your most recent push.

Going to consider this issue complete after tomorrow morning’s restart completes without error (assuming it does).

**Comment by adunkman** [comment] 2020-01-07 15:37
🎉 No more conflicting job runs! 
✖️ Recycle production is [still having issues](https://circleci.com/gh/18F/tock/5416).

**Comment by adunkman** [comment] 2020-01-08 15:48
Starting down the process of upgrading the CF CLI to see if it fixes the issue, but `cf-recycle-plugin` doesn’t appear to be compatible with the latest CF CLI: 

```
File is not a valid cf CLI plugin binary.
```

There is an equivalent and more recently maintained plugin, [cf-rolling-restart](https://github.com/homedepot/cf-rolling-restart), which works with the newer CLI as well as the older one. I’ll open a PR to switch over to this plugin to see if we have better results, and hold off upgrading the CF CLI for now in the spirit of only changing one thing at a time.

**Comment by tbaxter-18f** [comment] 2020-04-09 12:55
@adunkman I should have marked this "done", not "to-do", right?

**Comment by adunkman** [comment] 2020-04-09 13:16
I believe it is complete!

**Closed by adunkman** 2020-04-09 13:16 UTC
Labels: help wanted, triaged
