### ISSUE TITLE
Fix the `IndexError: list index out of range` at `/utilization/`

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#736] opened 2018-03-06 19:25 UTC
Looks like `/utilization/` is raising an `IndexError: list index out of range exception`.

_Discovered in #729_

### Acceptance Criteria
- [ ] Fix the `IndexError: list index out of range` at `/utilization/`

**Comment by tbaxter-18f** [comment] 2018-03-08 13:40
Roger, is there any particular way to trigger this error, or any extra info on where it's originating? I haven't been able to duplicate it.

**Comment by tbaxter-18f** [comment] 2018-03-19 15:09
@toolness pinging you too in case you may have some more context on this.

**Comment by toolness** [comment] 2018-03-19 15:20
Oh, you _should_ be able to reproduce it if you remove the permission check around that view and run `python manage.py test tock.tests.test_url_auth`--that's how I initially found the error. My guess is that this was happening because `test_url_auth` wasn't really initializing the database in any way, aside from the standard migrations, so perhaps this error is highly unlikely to actually occur in practice. If that's the case, or if you can't reproduce this error, feel free to close this issue!

**Comment by tbaxter-18f** [comment] 2018-03-19 18:56
It's an interesting error.

Removing the `PermissionMixin`, you can replicate the error in the test, as you expected.

However, actually going to to `/utilization` to mimic the `client` does _not_ produce it.

I have a working theory that it's related to `recent_rps` not having `[0]` to `[4]` indexes because the DB isn't initialized there, but I haven't been able to confirm, even with pdb. 

I think we should set this aside, at least for now, as I think it's _highly_ unlikely to occur outside of testing, and I think the effort would be better spent trying to optimize that view in general.

**Comment by toolness** [comment] 2018-03-19 19:08
Cool, that makes sense to me @tbaxter-18f ... thanks for looking into this! I'm closing the issue for now but feel free to re-open if anyone disagrees.

**Closed by toolness** 2018-03-19 19:08 UTC
Labels: help wanted
